### ISSUE TITLE
Would you consider relicensing your project to AGPL?

### ISSUE THREAD

**Issue by strypey** [beta-phenylethylamine/fontina#3]
Fontina is a wonderful idea for a free code software project, thanks so much for creating it. I note that you are releasing Fontina under a GNU GPLv3, which is great, it's a solid copyleft license. However, I wonder if you have considered putting your project under GNU AGPLv3? It's very similar to the GPL, but has a few extra clauses that address the special conditions created by software that can be accessed by users as a service over the internet, rather than downloaded and installed on their own computer. The main benefit for you is that it asserts that running a user-facing service using your code counts as "distribution", triggering the copyleft clauses, and obliging them to share a copy of the source code of your app (and any modifications they've made) with their users, and with you.

**Comment by rhaamo** [comment]
Isn't it already under AGPL ?

https://github.com/beta-phenylethylamine/fontina/blob/79681571f06b6c9e43cde38fe2e9855de851961f/LICENSE#L1-L2

**Comment by strypey** [comment]
On 2018-06-09 16:38, Marc Lagrange wrote:
> Isn't it already under AGPL ?

So it appears. Hmmm. Maybe I need to get glasses? Or stop pulling
all-nighters? Sorry to bother you :)
